// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/manga.proto

package mangapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Manga struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Genres        []string               `protobuf:"bytes,4,rep,name=genres,proto3" json:"genres,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TotalChapters int32                  `protobuf:"varint,6,opt,name=total_chapters,json=totalChapters,proto3" json:"total_chapters,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,8,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manga) Reset() {
	*x = Manga{}
	mi := &file_proto_manga_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manga) ProtoMessage() {}

func (x *Manga) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manga.ProtoReflect.Descriptor instead.
func (*Manga) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{0}
}

func (x *Manga) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manga) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Manga) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Manga) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *Manga) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Manga) GetTotalChapters() int32 {
	if x != nil {
		return x.TotalChapters
	}
	return 0
}

func (x *Manga) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Manga) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

type ListMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	Genres        []string               `protobuf:"bytes,2,rep,name=genres,proto3" json:"genres,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMangaRequest) Reset() {
	*x = ListMangaRequest{}
	mi := &file_proto_manga_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMangaRequest) ProtoMessage() {}

func (x *ListMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMangaRequest.ProtoReflect.Descriptor instead.
func (*ListMangaRequest) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{1}
}

func (x *ListMangaRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *ListMangaRequest) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *ListMangaRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListMangaRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMangaRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListMangaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Items         []*Manga               `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMangaResponse) Reset() {
	*x = ListMangaResponse{}
	mi := &file_proto_manga_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMangaResponse) ProtoMessage() {}

func (x *ListMangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMangaResponse.ProtoReflect.Descriptor instead.
func (*ListMangaResponse) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{2}
}

func (x *ListMangaResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListMangaResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMangaResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListMangaResponse) GetItems() []*Manga {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMangaRequest) Reset() {
	*x = GetMangaRequest{}
	mi := &file_proto_manga_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMangaRequest) ProtoMessage() {}

func (x *GetMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMangaRequest.ProtoReflect.Descriptor instead.
func (*GetMangaRequest) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{3}
}

func (x *GetMangaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMangaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manga         *Manga                 `protobuf:"bytes,1,opt,name=manga,proto3" json:"manga,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMangaResponse) Reset() {
	*x = GetMangaResponse{}
	mi := &file_proto_manga_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMangaResponse) ProtoMessage() {}

func (x *GetMangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMangaResponse.ProtoReflect.Descriptor instead.
func (*GetMangaResponse) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{4}
}

func (x *GetMangaResponse) GetManga() *Manga {
	if x != nil {
		return x.Manga
	}
	return nil
}

type ProgressItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MangaId        string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	CurrentChapter int32                  `protobuf:"varint,3,opt,name=current_chapter,json=currentChapter,proto3" json:"current_chapter,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	UpdatedAtUnix  int64                  `protobuf:"varint,5,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProgressItem) Reset() {
	*x = ProgressItem{}
	mi := &file_proto_manga_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressItem) ProtoMessage() {}

func (x *ProgressItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressItem.ProtoReflect.Descriptor instead.
func (*ProgressItem) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{5}
}

func (x *ProgressItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProgressItem) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

func (x *ProgressItem) GetCurrentChapter() int32 {
	if x != nil {
		return x.CurrentChapter
	}
	return 0
}

func (x *ProgressItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProgressItem) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

type ListProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProgressRequest) Reset() {
	*x = ListProgressRequest{}
	mi := &file_proto_manga_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProgressRequest) ProtoMessage() {}

func (x *ListProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProgressRequest.ProtoReflect.Descriptor instead.
func (*ListProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{6}
}

func (x *ListProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListProgressRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListProgressRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListProgressRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Items         []*ProgressItem        `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProgressResponse) Reset() {
	*x = ListProgressResponse{}
	mi := &file_proto_manga_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProgressResponse) ProtoMessage() {}

func (x *ListProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProgressResponse.ProtoReflect.Descriptor instead.
func (*ListProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{7}
}

func (x *ListProgressResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListProgressResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListProgressResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListProgressResponse) GetItems() []*ProgressItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MangaId       string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressRequest) Reset() {
	*x = GetProgressRequest{}
	mi := &file_proto_manga_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressRequest) ProtoMessage() {}

func (x *GetProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressRequest.ProtoReflect.Descriptor instead.
func (*GetProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{8}
}

func (x *GetProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetProgressRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

type GetProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ProgressItem          `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressResponse) Reset() {
	*x = GetProgressResponse{}
	mi := &file_proto_manga_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressResponse) ProtoMessage() {}

func (x *GetProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressResponse.ProtoReflect.Descriptor instead.
func (*GetProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{9}
}

func (x *GetProgressResponse) GetItem() *ProgressItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpsertProgressRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MangaId        string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	CurrentChapter int32                  `protobuf:"varint,3,opt,name=current_chapter,json=currentChapter,proto3" json:"current_chapter,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpsertProgressRequest) Reset() {
	*x = UpsertProgressRequest{}
	mi := &file_proto_manga_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertProgressRequest) ProtoMessage() {}

func (x *UpsertProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertProgressRequest.ProtoReflect.Descriptor instead.
func (*UpsertProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{10}
}

func (x *UpsertProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpsertProgressRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

func (x *UpsertProgressRequest) GetCurrentChapter() int32 {
	if x != nil {
		return x.CurrentChapter
	}
	return 0
}

func (x *UpsertProgressRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpsertProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ProgressItem          `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertProgressResponse) Reset() {
	*x = UpsertProgressResponse{}
	mi := &file_proto_manga_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertProgressResponse) ProtoMessage() {}

func (x *UpsertProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertProgressResponse.ProtoReflect.Descriptor instead.
func (*UpsertProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{11}
}

func (x *UpsertProgressResponse) GetItem() *ProgressItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MangaId       string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProgressRequest) Reset() {
	*x = DeleteProgressRequest{}
	mi := &file_proto_manga_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProgressRequest) ProtoMessage() {}

func (x *DeleteProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProgressRequest.ProtoReflect.Descriptor instead.
func (*DeleteProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteProgressRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

type DeleteProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProgressResponse) Reset() {
	*x = DeleteProgressResponse{}
	mi := &file_proto_manga_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProgressResponse) ProtoMessage() {}

func (x *DeleteProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProgressResponse.ProtoReflect.Descriptor instead.
func (*DeleteProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteProgressResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_proto_manga_proto protoreflect.FileDescriptor

const file_proto_manga_proto_rawDesc = "" +
	"\n" +
	"\x11proto/manga.proto\x12\vmangahub.v1\"\xdb\x01\n" +
	"\x05Manga\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x16\n" +
	"\x06genres\x18\x04 \x03(\tR\x06genres\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12%\n" +
	"\x0etotal_chapters\x18\x06 \x01(\x05R\rtotalChapters\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1b\n" +
	"\tcover_url\x18\b \x01(\tR\bcoverUrl\"~\n" +
	"\x10ListMangaRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\x12\x16\n" +
	"\x06genres\x18\x02 \x03(\tR\x06genres\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"\x81\x01\n" +
	"\x11ListMangaResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12(\n" +
	"\x05items\x18\x04 \x03(\v2\x12.mangahub.v1.MangaR\x05items\"!\n" +
	"\x0fGetMangaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x10GetMangaResponse\x12(\n" +
	"\x05manga\x18\x01 \x01(\v2\x12.mangahub.v1.MangaR\x05manga\"\xab\x01\n" +
	"\fProgressItem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\x12'\n" +
	"\x0fcurrent_chapter\x18\x03 \x01(\x05R\x0ecurrentChapter\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12&\n" +
	"\x0fupdated_at_unix\x18\x05 \x01(\x03R\rupdatedAtUnix\"t\n" +
	"\x13ListProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\x8b\x01\n" +
	"\x14ListProgressResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12/\n" +
	"\x05items\x18\x04 \x03(\v2\x19.mangahub.v1.ProgressItemR\x05items\"H\n" +
	"\x12GetProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\"D\n" +
	"\x13GetProgressResponse\x12-\n" +
	"\x04item\x18\x01 \x01(\v2\x19.mangahub.v1.ProgressItemR\x04item\"\x8c\x01\n" +
	"\x15UpsertProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\x12'\n" +
	"\x0fcurrent_chapter\x18\x03 \x01(\x05R\x0ecurrentChapter\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"G\n" +
	"\x16UpsertProgressResponse\x12-\n" +
	"\x04item\x18\x01 \x01(\v2\x19.mangahub.v1.ProgressItemR\x04item\"K\n" +
	"\x15DeleteProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\"2\n" +
	"\x16DeleteProgressResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted2\xa3\x01\n" +
	"\fMangaService\x12J\n" +
	"\tListManga\x12\x1d.mangahub.v1.ListMangaRequest\x1a\x1e.mangahub.v1.ListMangaResponse\x12G\n" +
	"\bGetManga\x12\x1c.mangahub.v1.GetMangaRequest\x1a\x1d.mangahub.v1.GetMangaResponse2\xee\x02\n" +
	"\x0fProgressService\x12S\n" +
	"\fListProgress\x12 .mangahub.v1.ListProgressRequest\x1a!.mangahub.v1.ListProgressResponse\x12P\n" +
	"\vGetProgress\x12\x1f.mangahub.v1.GetProgressRequest\x1a .mangahub.v1.GetProgressResponse\x12Y\n" +
	"\x0eUpsertProgress\x12\".mangahub.v1.UpsertProgressRequest\x1a#.mangahub.v1.UpsertProgressResponse\x12Y\n" +
	"\x0eDeleteProgress\x12\".mangahub.v1.DeleteProgressRequest\x1a#.mangahub.v1.DeleteProgressResponseB#Z!mangahub/pkg/grpc/mangapb;mangapbb\x06proto3"

var (
	file_proto_manga_proto_rawDescOnce sync.Once
	file_proto_manga_proto_rawDescData []byte
)

func file_proto_manga_proto_rawDescGZIP() []byte {
	file_proto_manga_proto_rawDescOnce.Do(func() {
		file_proto_manga_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_manga_proto_rawDesc), len(file_proto_manga_proto_rawDesc)))
	})
	return file_proto_manga_proto_rawDescData
}

var file_proto_manga_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_manga_proto_goTypes = []any{
	(*Manga)(nil),                  // 0: mangahub.v1.Manga
	(*ListMangaRequest)(nil),       // 1: mangahub.v1.ListMangaRequest
	(*ListMangaResponse)(nil),      // 2: mangahub.v1.ListMangaResponse
	(*GetMangaRequest)(nil),        // 3: mangahub.v1.GetMangaRequest
	(*GetMangaResponse)(nil),       // 4: mangahub.v1.GetMangaResponse
	(*ProgressItem)(nil),           // 5: mangahub.v1.ProgressItem
	(*ListProgressRequest)(nil),    // 6: mangahub.v1.ListProgressRequest
	(*ListProgressResponse)(nil),   // 7: mangahub.v1.ListProgressResponse
	(*GetProgressRequest)(nil),     // 8: mangahub.v1.GetProgressRequest
	(*GetProgressResponse)(nil),    // 9: mangahub.v1.GetProgressResponse
	(*UpsertProgressRequest)(nil),  // 10: mangahub.v1.UpsertProgressRequest
	(*UpsertProgressResponse)(nil), // 11: mangahub.v1.UpsertProgressResponse
	(*DeleteProgressRequest)(nil),  // 12: mangahub.v1.DeleteProgressRequest
	(*DeleteProgressResponse)(nil), // 13: mangahub.v1.DeleteProgressResponse
}
var file_proto_manga_proto_depIdxs = []int32{
	0,  // 0: mangahub.v1.ListMangaResponse.items:type_name -> mangahub.v1.Manga
	0,  // 1: mangahub.v1.GetMangaResponse.manga:type_name -> mangahub.v1.Manga
	5,  // 2: mangahub.v1.ListProgressResponse.items:type_name -> mangahub.v1.ProgressItem
	5,  // 3: mangahub.v1.GetProgressResponse.item:type_name -> mangahub.v1.ProgressItem
	5,  // 4: mangahub.v1.UpsertProgressResponse.item:type_name -> mangahub.v1.ProgressItem
	1,  // 5: mangahub.v1.MangaService.ListManga:input_type -> mangahub.v1.ListMangaRequest
	3,  // 6: mangahub.v1.MangaService.GetManga:input_type -> mangahub.v1.GetMangaRequest
	6,  // 7: mangahub.v1.ProgressService.ListProgress:input_type -> mangahub.v1.ListProgressRequest
	8,  // 8: mangahub.v1.ProgressService.GetProgress:input_type -> mangahub.v1.GetProgressRequest
	10, // 9: mangahub.v1.ProgressService.UpsertProgress:input_type -> mangahub.v1.UpsertProgressRequest
	12, // 10: mangahub.v1.ProgressService.DeleteProgress:input_type -> mangahub.v1.DeleteProgressRequest
	2,  // 11: mangahub.v1.MangaService.ListManga:output_type -> mangahub.v1.ListMangaResponse
	4,  // 12: mangahub.v1.MangaService.GetManga:output_type -> mangahub.v1.GetMangaResponse
	7,  // 13: mangahub.v1.ProgressService.ListProgress:output_type -> mangahub.v1.ListProgressResponse
	9,  // 14: mangahub.v1.ProgressService.GetProgress:output_type -> mangahub.v1.GetProgressResponse
	11, // 15: mangahub.v1.ProgressService.UpsertProgress:output_type -> mangahub.v1.UpsertProgressResponse
	13, // 16: mangahub.v1.ProgressService.DeleteProgress:output_type -> mangahub.v1.DeleteProgressResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_manga_proto_init() }
func file_proto_manga_proto_init() {
	if File_proto_manga_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_manga_proto_rawDesc), len(file_proto_manga_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_manga_proto_goTypes,
		DependencyIndexes: file_proto_manga_proto_depIdxs,
		MessageInfos:      file_proto_manga_proto_msgTypes,
	}.Build()
	File_proto_manga_proto = out.File
	file_proto_manga_proto_goTypes = nil
	file_proto_manga_proto_depIdxs = nil
}
